const String whyNeedText =
    "Why do I need to provide the following information? \n\nFor a better peer to peer connectivity and to help make better decisions while trying to connect with other users, profession, education level and gender is made visible to other users. Any other personal information is kept private and will only be used where necessary for your own security or advantage. Government/National id/Passport/DL verified user means that the person is accountable for his/her actions. Each and every user is verified so you can connect with other users with confidence.";
const String nidText =
    "Why do I need to provide Govt id/NID/Passport/DL information? \n We require you to provide Government id/National id/Passport/DL information for your own safety and security. A verified user means that the person is accountable for his/her actions. It is to prevent/avoid unpleasant experience while interacting with other users as each member is held responsible for his/her unwanted actions.For passport photos, provide the page containing the photo and the page that contains your name and other information.";
const String educationText = "Why do I need to provide information about my education? \n For a better peer to peer connectivity and to help make better decisions while trying to connect with other users.";
const String professionText = "Why do I need to provide information about my profession?  \nFor a better peer to peer connectivity and to help make better decisions while trying to connect with other users.";
const String securityQesText = "Why do I need to provide a security question?\n Security question is to add an extra layer of certainty to identify you when you have forgotten your password, entered the wrong credentials too many times, or tried to log in from an unfamiliar device or location.";
const String securityAnsText = "Why do I need to provide a security answer?\n Security answer is to ensure your identity when you have forgotten your password, entered the wrong credentials too many times, or tried to log in from an unfamiliar device or location.";
const String optionalText = "Optional Information \nAlthough the information sought here is optional, it is highly recommended that you provide them for your own security or advantage. TripShipTask may use the information to your benefit should you face any emergency situation.";
const String bloodText = "Why should I provide my blood group information? \nThis data is kept safe and secure and may be used for your benefit if and when necessary in any medical emergency and never shared with any other user.";
const String residenceText = "Why should I provide my residence area? \nThis helps you get better results in connecting with trips, shipments and tasks and hence improves your chances of making more money. This information is not made public";
const String emergencyPersonName = "Why should I provide an emergency contact person's name? \n This data is kept safe and secure and may be used for your advantage if and when necessary in any emergency and never shared with any other user.";
const String emergencyPersonNumer = "Emergency Contact Number \nThis data is kept safe and secure and may be used for your advantage if and when necessary in any emergency and never shared with any other user.";
const String facebookText = "Why should I provide my facebook profile link? \n This helps you get more information about the user and understand who their connections are. You can have a better sense of security by understanding their social stand.";
const String nomineeText = "Why should I provide a nominee name? \n If you part from this world, your nominee will receive the money that you leave in your account (if any) and/or shall continue to receive referral incentives for the next 100 years from the day you part from this world given that the nominee provide proper identification of themselves that matches the description you provided in the system.";